# Generated by Django 2.2.14 on 2022-12-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancoPregunta', '0003_auto_20221210_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='resultado',
            field=models.TextField(null=True),
        ),
    ]
